version: "3.9"
services:
  homebridge:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "1.6.1"
        HOMEBRIDGE_VERSION: "1.6.1"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "homebridge:dev"
    image: "gautada/homebridge:dev"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: "homebridge"
    ports:
      - "8888:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volumes/container/development/container
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volumes/container/development/backup
      
