version: "3.9"
services:
  dashy:
    build:
      args:
        ALPINE_VERSION: "latest"
        DASHY_VERSION: "2.1.1"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "homebridge:dev"
    image: "homebridge:dev"
    ports:
      - "8080:8080"
      - "51400:51400"
      - "5353:5353"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/homebridge/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/homebridge/backup-volume
      
