kind: pipeline
type: kubernetes
name: container_integration

steps:
- name: integrate
  image: gautada/builder:v1.21.4_v3.2.3
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: username.docker.io
    DOCKER_PASSWORD:
      from_secret: password.docker.io
    ALPINE_TAG: 3.14.1
    OCI_VERSION: r1.3.4
  commands:
  - buildah login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD docker.io
  - buildah bud --build-arg ALPINE_TAG=$ALPINE_TAG --tag homebridge:dev -f Containerfile
  - buildah push localhost/homebridge:dev docker://docker.io/gautada/homebridge:$OCI_VERSION

trigger:
  branch:
  - main


kind: pipeline
type: exec
name: Development Build - Homebridge

platform:
  os: linux
  arch: arm64

steps:
- name: build
  environment:
    ALPINE_VERSION: 3.15.4
    HOMEBRIDGE_VERSION: 1.4.1
  commands:
  - podman build --build-arg ALPINE_VERSION=$ALPINE_VERSION --build-arg HOMEBRIDGE_VERSION=$HOMEBRIDGE_VERSION --format docker --file Containerfile --label revision="$(git rev-parse HEAD)" --label version="$(date +%Y.%m.%d)" --no-cache --tag homebridge:build .

- name: publish
  environment:
    HOMEBRIDGE_VERSION: 1.4.1
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
   - podman tag homebridge:build docker.io/gautada/coredns:$HOMEBRIDGE_VERSION
   - podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
   - podman push docker.io/gautada/homebridge:$HOMEBRIDGE_VERSION
  
