#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

APP_NAME="homebridge"

app_version() {
 /usr/local/lib/node_modules/homebridge/bin/homebridge  --version
}

log "-i" "entrypoint" "Launch Application - $APP_NAME($(app_version))"
if [ -z "$@" ] ; then
 /usr/local/lib/node_modules/homebridge/bin/homebridge --debug | /usr/bin/tee /mnt/volumes/container/homebridge.log >> /dev/stdout
 return 1
else
  log "-i" "entrypoint" "Launch Application [BACKGROUND]"
  /usr/local/lib/node_modules/homebridge/bin/homebridge --debug > /mnt/volumes/container/homebridge.log 2>&1 &
return 0
fi
