#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"

app_version() {
 /usr/local/lib/node_modules/homebridge/bin/homebridge  --version
}

container_entrypoint() {
 /usr/local/lib/node_modules/homebridge/bin/homebridge --debug 
}
